# Currently using node 8.x - this is newest version recommended for production and so most widely supported by packages,
# this will change in April 2019 (https://github.com/nodejs/Release)
#
# When caching node dependencies we include node version as some dependencies may vary also on a per node version basis.


version: 2.1
executors:
  node-browsers-local-api:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/repo
    environment:
      PP_API: local

  node-pp-api:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    environment:
      PP_API: pp
      PP_DEV: false

jobs:
  install:
    executor: node-browsers-local-api
    steps:
      - checkout
      - restore_cache:
          keys:
          - v2-node-8-dependencies-{{ checksum "package-lock.json" }}-and-{{ checksum "package.json" }}
      - run: test -e node_modules || npm ci
      - save_cache:
          paths:
            - node_modules
          key: v2-node-8-dependencies-{{ checksum "package-lock.json" }}-and-{{ checksum "package.json" }}

  test:
    executor: node-browsers-local-api
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-node-8-dependencies-{{ checksum "package-lock.json" }}-and-{{ checksum "package.json" }}
      - run: npm run test

  e2e-build:
    executor: node-browsers-local-api
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-node-8-dependencies-{{ checksum "package-lock.json" }}-and-{{ checksum "package.json" }}
      - run: npm run build
      - run: npm run e2e

  e2e-build-optimized:
    executor: node-browsers-local-api
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-node-8-dependencies-{{ checksum "package-lock.json" }}-and-{{ checksum "package.json" }}
      - run: npm run build-optimized
      - run: npm run e2e

  release:
    executor: node-pp-api
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-node-8-dependencies-{{ checksum "package-lock.json" }}-and-{{ checksum "package.json" }}
      - run: npm run build-package
      - run:
          name: add version number to the package
          command: |
            mkdir dist/package;
            mv dist/pp-chrome.zip dist/package/pp-chrome-$CIRCLE_TAG.zip;
      - store_artifacts:
          path: dist/package/
          destination: package

workflows:
  version: 2
  install-test-release:
    jobs:
      - install:
          filters:
            tags: # required since `release` has tag filters AND requires this job
              only: /.*/
      - test:
          requires:
            - install
          filters:
            tags: # required since `release` has tag filters AND requires this job
              only: /.*/
      - e2e-build:
          requires:
            - install
          filters:
            tags: # required since `release` has tag filters AND requires this job
              only: /.*/
      - e2e-build-optimized:
          requires:
            - install
          filters:
            tags: # required since `release` has tag filters AND requires this job
              only: /.*/
      - release:
          requires:
            - install
            - test
            - e2e-build
            - e2e-build-optimized
          filters:
            branches: # no branches, now tag condition can filter commits with proper tag
              ignore: /.*/
            tags:
              only: /v.+/
